/*
 * Forge SDK
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: forge.help@autodesk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.autodesk.client.model;

import java.util.Objects;

import com.autodesk.client.model.CreateItemRelationshipsStorage;
import com.autodesk.client.model.CreateVersionDataRelationshipsItem;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * CreateVersionDataRelationships
 */

public class CreateVersionDataRelationships   {
  @JsonProperty("item")
  private CreateVersionDataRelationshipsItem item = null;

  @JsonProperty("storage")
  private CreateItemRelationshipsStorage storage = null;

  public CreateVersionDataRelationships item(CreateVersionDataRelationshipsItem item) {
    this.item = item;
    return this;
  }

   /**
   * Get item
   * @return item
  **/
  @ApiModelProperty(example = "null", value = "")
  public CreateVersionDataRelationshipsItem getItem() {
    return item;
  }

  public void setItem(CreateVersionDataRelationshipsItem item) {
    this.item = item;
  }

  public CreateVersionDataRelationships storage(CreateItemRelationshipsStorage storage) {
    this.storage = storage;
    return this;
  }

   /**
   * Get storage
   * @return storage
  **/
  @ApiModelProperty(example = "null", value = "")
  public CreateItemRelationshipsStorage getStorage() {
    return storage;
  }

  public void setStorage(CreateItemRelationshipsStorage storage) {
    this.storage = storage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateVersionDataRelationships createVersionDataRelationships = (CreateVersionDataRelationships) o;
    return Objects.equals(this.item, createVersionDataRelationships.item) &&
        Objects.equals(this.storage, createVersionDataRelationships.storage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(item, storage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateVersionDataRelationships {\n");
    
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("    storage: ").append(toIndentedString(storage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

