/*
 * Forge SDK
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: forge.help@autodesk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.autodesk.client.model;

import java.util.Objects;

import com.autodesk.client.model.JsonApiRelationshipsLinksInternal;
import com.autodesk.client.model.JsonApiRelationshipsLinksInternalResource;
import com.autodesk.client.model.JsonApiRelationshipsLinksRefs;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * FolderRelationships
 */

public class FolderRelationships   {
  @JsonProperty("parent")
  private JsonApiRelationshipsLinksInternalResource parent = null;

  @JsonProperty("contents")
  private JsonApiRelationshipsLinksInternal contents = null;

  @JsonProperty("refs")
  private JsonApiRelationshipsLinksRefs refs = null;

  public FolderRelationships parent(JsonApiRelationshipsLinksInternalResource parent) {
    this.parent = parent;
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  @ApiModelProperty(example = "null", value = "")
  public JsonApiRelationshipsLinksInternalResource getParent() {
    return parent;
  }

  public void setParent(JsonApiRelationshipsLinksInternalResource parent) {
    this.parent = parent;
  }

  public FolderRelationships contents(JsonApiRelationshipsLinksInternal contents) {
    this.contents = contents;
    return this;
  }

   /**
   * Get contents
   * @return contents
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public JsonApiRelationshipsLinksInternal getContents() {
    return contents;
  }

  public void setContents(JsonApiRelationshipsLinksInternal contents) {
    this.contents = contents;
  }

  public FolderRelationships refs(JsonApiRelationshipsLinksRefs refs) {
    this.refs = refs;
    return this;
  }

   /**
   * Get refs
   * @return refs
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public JsonApiRelationshipsLinksRefs getRefs() {
    return refs;
  }

  public void setRefs(JsonApiRelationshipsLinksRefs refs) {
    this.refs = refs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FolderRelationships folderRelationships = (FolderRelationships) o;
    return Objects.equals(this.parent, folderRelationships.parent) &&
        Objects.equals(this.contents, folderRelationships.contents) &&
        Objects.equals(this.refs, folderRelationships.refs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parent, contents, refs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FolderRelationships {\n");
    
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    contents: ").append(toIndentedString(contents)).append("\n");
    sb.append("    refs: ").append(toIndentedString(refs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

