/*
 * Forge SDK
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: forge.help@autodesk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.autodesk.client.model;

import java.util.Objects;

import com.autodesk.client.model.JsonApiRelationshipsLinksExternalResource;
import com.autodesk.client.model.JsonApiRelationshipsLinksInternalResource;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * ProjectRelationships
 */

public class ProjectRelationships   {
  @JsonProperty("hub")
  private JsonApiRelationshipsLinksInternalResource hub = null;

  @JsonProperty("rootFolder")
  private JsonApiRelationshipsLinksExternalResource rootFolder = null;

  public ProjectRelationships hub(JsonApiRelationshipsLinksInternalResource hub) {
    this.hub = hub;
    return this;
  }

   /**
   * Get hub
   * @return hub
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public JsonApiRelationshipsLinksInternalResource getHub() {
    return hub;
  }

  public void setHub(JsonApiRelationshipsLinksInternalResource hub) {
    this.hub = hub;
  }

  public ProjectRelationships rootFolder(JsonApiRelationshipsLinksExternalResource rootFolder) {
    this.rootFolder = rootFolder;
    return this;
  }

   /**
   * Get rootFolder
   * @return rootFolder
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public JsonApiRelationshipsLinksExternalResource getRootFolder() {
    return rootFolder;
  }

  public void setRootFolder(JsonApiRelationshipsLinksExternalResource rootFolder) {
    this.rootFolder = rootFolder;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectRelationships projectRelationships = (ProjectRelationships) o;
    return Objects.equals(this.hub, projectRelationships.hub) &&
        Objects.equals(this.rootFolder, projectRelationships.rootFolder);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hub, rootFolder);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectRelationships {\n");
    
    sb.append("    hub: ").append(toIndentedString(hub)).append("\n");
    sb.append("    rootFolder: ").append(toIndentedString(rootFolder)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

