/*
 * Forge SDK
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: forge.help@autodesk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.autodesk.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * WorkItemResp
 */

public class WorkItemResp   {
  @JsonProperty("Id")
  private String id = null;

  @JsonProperty("Arguments")
  private Object arguments = null;

  @JsonProperty("Status")
  private String status = null;

  @JsonProperty("StatusDetail")
  private Object statusDetail = null;

  @JsonProperty("AvailabilityZone")
  private String availabilityZone = null;

  @JsonProperty("ActivityId")
  private String activityId = null;

  @JsonProperty("Version")
  private Integer version = null;

  @JsonProperty("Timestamp")
  private String timestamp = null;

  @JsonProperty("TimeQueued")
  private String timeQueued = null;

  @JsonProperty("TimeInputTransferStarted")
  private String timeInputTransferStarted = null;

  @JsonProperty("TimeScriptStarted")
  private String timeScriptStarted = null;

  @JsonProperty("TimeScriptEnded")
  private String timeScriptEnded = null;

  @JsonProperty("TimeOutputTransferEnded")
  private String timeOutputTransferEnded = null;

  @JsonProperty("BytesTranferredIn")
  private Integer bytesTranferredIn = null;

  @JsonProperty("BytesTranferredOut")
  private Integer bytesTranferredOut = null;

  public WorkItemResp id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public WorkItemResp arguments(Object arguments) {
    this.arguments = arguments;
    return this;
  }

   /**
   * Get arguments
   * @return arguments
  **/
  @ApiModelProperty(example = "null", value = "")
  public Object getArguments() {
    return arguments;
  }

  public void setArguments(Object arguments) {
    this.arguments = arguments;
  }

  public WorkItemResp status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public WorkItemResp statusDetail(Object statusDetail) {
    this.statusDetail = statusDetail;
    return this;
  }

   /**
   * Get statusDetail
   * @return statusDetail
  **/
  @ApiModelProperty(example = "null", value = "")
  public Object getStatusDetail() {
    return statusDetail;
  }

  public void setStatusDetail(Object statusDetail) {
    this.statusDetail = statusDetail;
  }

  public WorkItemResp availabilityZone(String availabilityZone) {
    this.availabilityZone = availabilityZone;
    return this;
  }

   /**
   * Get availabilityZone
   * @return availabilityZone
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAvailabilityZone() {
    return availabilityZone;
  }

  public void setAvailabilityZone(String availabilityZone) {
    this.availabilityZone = availabilityZone;
  }

  public WorkItemResp activityId(String activityId) {
    this.activityId = activityId;
    return this;
  }

   /**
   * Get activityId
   * @return activityId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getActivityId() {
    return activityId;
  }

  public void setActivityId(String activityId) {
    this.activityId = activityId;
  }

  public WorkItemResp version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  public WorkItemResp timestamp(String timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(String timestamp) {
    this.timestamp = timestamp;
  }

  public WorkItemResp timeQueued(String timeQueued) {
    this.timeQueued = timeQueued;
    return this;
  }

   /**
   * Get timeQueued
   * @return timeQueued
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTimeQueued() {
    return timeQueued;
  }

  public void setTimeQueued(String timeQueued) {
    this.timeQueued = timeQueued;
  }

  public WorkItemResp timeInputTransferStarted(String timeInputTransferStarted) {
    this.timeInputTransferStarted = timeInputTransferStarted;
    return this;
  }

   /**
   * Get timeInputTransferStarted
   * @return timeInputTransferStarted
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTimeInputTransferStarted() {
    return timeInputTransferStarted;
  }

  public void setTimeInputTransferStarted(String timeInputTransferStarted) {
    this.timeInputTransferStarted = timeInputTransferStarted;
  }

  public WorkItemResp timeScriptStarted(String timeScriptStarted) {
    this.timeScriptStarted = timeScriptStarted;
    return this;
  }

   /**
   * Get timeScriptStarted
   * @return timeScriptStarted
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTimeScriptStarted() {
    return timeScriptStarted;
  }

  public void setTimeScriptStarted(String timeScriptStarted) {
    this.timeScriptStarted = timeScriptStarted;
  }

  public WorkItemResp timeScriptEnded(String timeScriptEnded) {
    this.timeScriptEnded = timeScriptEnded;
    return this;
  }

   /**
   * Get timeScriptEnded
   * @return timeScriptEnded
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTimeScriptEnded() {
    return timeScriptEnded;
  }

  public void setTimeScriptEnded(String timeScriptEnded) {
    this.timeScriptEnded = timeScriptEnded;
  }

  public WorkItemResp timeOutputTransferEnded(String timeOutputTransferEnded) {
    this.timeOutputTransferEnded = timeOutputTransferEnded;
    return this;
  }

   /**
   * Get timeOutputTransferEnded
   * @return timeOutputTransferEnded
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTimeOutputTransferEnded() {
    return timeOutputTransferEnded;
  }

  public void setTimeOutputTransferEnded(String timeOutputTransferEnded) {
    this.timeOutputTransferEnded = timeOutputTransferEnded;
  }

  public WorkItemResp bytesTranferredIn(Integer bytesTranferredIn) {
    this.bytesTranferredIn = bytesTranferredIn;
    return this;
  }

   /**
   * Get bytesTranferredIn
   * @return bytesTranferredIn
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBytesTranferredIn() {
    return bytesTranferredIn;
  }

  public void setBytesTranferredIn(Integer bytesTranferredIn) {
    this.bytesTranferredIn = bytesTranferredIn;
  }

  public WorkItemResp bytesTranferredOut(Integer bytesTranferredOut) {
    this.bytesTranferredOut = bytesTranferredOut;
    return this;
  }

   /**
   * Get bytesTranferredOut
   * @return bytesTranferredOut
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBytesTranferredOut() {
    return bytesTranferredOut;
  }

  public void setBytesTranferredOut(Integer bytesTranferredOut) {
    this.bytesTranferredOut = bytesTranferredOut;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkItemResp workItemResp = (WorkItemResp) o;
    return Objects.equals(this.id, workItemResp.id) &&
        Objects.equals(this.arguments, workItemResp.arguments) &&
        Objects.equals(this.status, workItemResp.status) &&
        Objects.equals(this.statusDetail, workItemResp.statusDetail) &&
        Objects.equals(this.availabilityZone, workItemResp.availabilityZone) &&
        Objects.equals(this.activityId, workItemResp.activityId) &&
        Objects.equals(this.version, workItemResp.version) &&
        Objects.equals(this.timestamp, workItemResp.timestamp) &&
        Objects.equals(this.timeQueued, workItemResp.timeQueued) &&
        Objects.equals(this.timeInputTransferStarted, workItemResp.timeInputTransferStarted) &&
        Objects.equals(this.timeScriptStarted, workItemResp.timeScriptStarted) &&
        Objects.equals(this.timeScriptEnded, workItemResp.timeScriptEnded) &&
        Objects.equals(this.timeOutputTransferEnded, workItemResp.timeOutputTransferEnded) &&
        Objects.equals(this.bytesTranferredIn, workItemResp.bytesTranferredIn) &&
        Objects.equals(this.bytesTranferredOut, workItemResp.bytesTranferredOut);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, arguments, status, statusDetail, availabilityZone, activityId, version, timestamp, timeQueued, timeInputTransferStarted, timeScriptStarted, timeScriptEnded, timeOutputTransferEnded, bytesTranferredIn, bytesTranferredOut);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkItemResp {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    arguments: ").append(toIndentedString(arguments)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusDetail: ").append(toIndentedString(statusDetail)).append("\n");
    sb.append("    availabilityZone: ").append(toIndentedString(availabilityZone)).append("\n");
    sb.append("    activityId: ").append(toIndentedString(activityId)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    timeQueued: ").append(toIndentedString(timeQueued)).append("\n");
    sb.append("    timeInputTransferStarted: ").append(toIndentedString(timeInputTransferStarted)).append("\n");
    sb.append("    timeScriptStarted: ").append(toIndentedString(timeScriptStarted)).append("\n");
    sb.append("    timeScriptEnded: ").append(toIndentedString(timeScriptEnded)).append("\n");
    sb.append("    timeOutputTransferEnded: ").append(toIndentedString(timeOutputTransferEnded)).append("\n");
    sb.append("    bytesTranferredIn: ").append(toIndentedString(bytesTranferredIn)).append("\n");
    sb.append("    bytesTranferredOut: ").append(toIndentedString(bytesTranferredOut)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

